[plugin]
id = "mssql-compiler-plugin"
class = "io.ballerina.stdlib.mssql.compiler.MSSQLCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/mssql-compiler-plugin-1.10.0-SNAPSHOT.jar"
